#pragma once

#define G_GAMEPAD_BUTTON_A				0
#define G_GAMEPAD_BUTTON_B				1
#define G_GAMEPAD_BUTTON_X				2
#define G_GAMEPAD_BUTTON_Y				3
#define G_GAMEPAD_BUTTON_LEFT_BUMPER	4
#define G_GAMEPAD_BUTTON_RIGHT_BUMPER   5
#define G_GAMEPAD_BUTTON_BACK			6
#define G_GAMEPAD_BUTTON_START			7
#define G_GAMEPAD_BUTTON_GUIDE			8
#define G_GAMEPAD_BUTTON_LEFT_THUMB		9
#define G_GAMEPAD_BUTTON_RIGHT_THUMB	10
#define G_GAMEPAD_BUTTON_DPAD_UP		11
#define G_GAMEPAD_BUTTON_DPAD_RIGHT		12
#define G_GAMEPAD_BUTTON_DPAD_DOWN		13
#define G_GAMEPAD_BUTTON_DPAD_LEFT		14
#define G_GAMEPAD_BUTTON_CROSS			G_GAMEPAD_BUTTON_A	//0
#define G_GAMEPAD_BUTTON_CIRCLE			G_GAMEPAD_BUTTON_B	//1
#define G_GAMEPAD_BUTTON_SQUARE			G_GAMEPAD_BUTTON_X	//2
#define G_GAMEPAD_BUTTON_TRIANGLE		G_GAMEPAD_BUTTON_Y	//3
