#pragma once

#define G_MOUSE_BUTTON_1		0
#define G_MOUSE_BUTTON_2		1
#define G_MOUSE_BUTTON_3		2
#define G_MOUSE_BUTTON_4		3
#define G_MOUSE_BUTTON_5		4
#define G_MOUSE_BUTTON_6		5
#define G_MOUSE_BUTTON_7		6
#define G_MOUSE_BUTTON_8		7
#define G_MOUSE_BUTTON_LEFT		G_MOUSE_BUTTON_1	//0
#define G_MOUSE_BUTTON_RIGHT	G_MOUSE_BUTTON_2	//1
#define G_MOUSE_BUTTON_MIDDLE	G_MOUSE_BUTTON_3	//2